# frozen_string_literal: true

source "https://rubygems.org"

gem "compute_runtime", path: "../"
gem "ruby_wasm", git: "https://github.com/ruby/ruby.wasm.git", ref: "f98b50c38e3d27329928e149f9f6c87cfe847f3f"
